fix(deps): Update dependency pytest to v8.2.0 (#80)
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [pytest](https://togithub.com/pytest-dev/pytest) ([changelog](https://docs.pytest.org/en/stable/changelog.html)) | minor | `==8.1.1` -> `==8.2.0` |

---

### Release Notes

<details>
<summary>pytest-dev/pytest (pytest)</summary>

### [`v8.2.0`](https://togithub.com/pytest-dev/pytest/releases/tag/8.2.0)

[Compare Source](https://togithub.com/pytest-dev/pytest/compare/8.1.2...8.2.0)

# pytest 8.2.0 (2024-04-27)

## Deprecations

-   [#&#8203;12069](https://togithub.com/pytest-dev/pytest/issues/12069): A deprecation warning is now raised when implementations of one of the following hooks request a deprecated `py.path.local` parameter instead of the `pathlib.Path` parameter which replaced it:

    -   `pytest_ignore_collect`{.interpreted-text role="hook"} - the `path` parameter - use `collection_path` instead.
    -   `pytest_collect_file`{.interpreted-text role="hook"} - the `path` parameter - use `file_path` instead.
    -   `pytest_pycollect_makemodule`{.interpreted-text role="hook"} - the `path` parameter - use `module_path` instead.
    -   `pytest_report_header`{.interpreted-text role="hook"} - the `startdir` parameter - use `start_path` instead.
    -   `pytest_report_collectionfinish`{.interpreted-text role="hook"} - the `startdir` parameter - use `start_path` instead.

    The replacement parameters are available since pytest 7.0.0.
    The old parameters will be removed in pytest 9.0.0.

    See `legacy-path-hooks-deprecated`{.interpreted-text role="ref"} for more details.

## Features

-   [#&#8203;11871](https://togithub.com/pytest-dev/pytest/issues/11871): Added support for reading command line arguments from a file using the prefix character `@`, like e.g.: `pytest @&#8203;tests.txt`. The file must have one argument per line.

    See `Read arguments from file <args-from-file>`{.interpreted-text role="ref"} for details.

## Improvements

-   [#&#8203;11523](https://togithub.com/pytest-dev/pytest/issues/11523): `pytest.importorskip`{.interpreted-text role="func"} will now issue a warning if the module could be found, but raised `ImportError`{.interpreted-text role="class"} instead of `ModuleNotFoundError`{.interpreted-text role="class"}.

    The warning can be suppressed by passing `exc_type=ImportError` to `pytest.importorskip`{.interpreted-text role="func"}.

    See `import-or-skip-import-error`{.interpreted-text role="ref"} for details.

-   [#&#8203;11728](https://togithub.com/pytest-dev/pytest/issues/11728): For `unittest`-based tests, exceptions during class cleanup (as raised by functions registered with `TestCase.addClassCleanup <unittest.TestCase.addClassCleanup>`{.interpreted-text role="meth"}) are now reported instead of silently failing.

-   [#&#8203;11777](https://togithub.com/pytest-dev/pytest/issues/11777): Text is no longer truncated in the `short test summary info` section when `-vv` is given.

-   [#&#8203;12112](https://togithub.com/pytest-dev/pytest/issues/12112): Improved namespace packages detection when `consider_namespace_packages`{.interpreted-text role="confval"} is enabled, covering more situations (like editable installs).

-   [#&#8203;9502](https://togithub.com/pytest-dev/pytest/issues/9502): Added `PYTEST_VERSION`{.interpreted-text role="envvar"} environment variable which is defined at the start of the pytest session and undefined afterwards. It contains the value of `pytest.__version__`, and among other things can be used to easily check if code is running from within a pytest run.

## Bug Fixes

-   [#&#8203;12065](https://togithub.com/pytest-dev/pytest/issues/12065): Fixed a regression in pytest 8.0.0 where test classes containing `setup_method` and tests using `@staticmethod` or `@classmethod` would crash with `AttributeError: 'NoneType' object has no attribute 'setup_method'`.

    Now the `request.instance <pytest.FixtureRequest.instance>`{.interpreted-text role="attr"} attribute of tests using `@staticmethod` and `@classmethod` is no longer `None`, but a fresh instance of the class, like in non-static methods.
    Previously it was `None`, and all fixtures of such tests would share a single `self`.

-   [#&#8203;12135](https://togithub.com/pytest-dev/pytest/issues/12135): Fixed issue where fixtures adding their finalizer multiple times to fixtures they request would cause unreliable and non-intuitive teardown ordering in some instances.

-   [#&#8203;12194](https://togithub.com/pytest-dev/pytest/issues/12194): Fixed a bug with `--importmode=importlib` and `--doctest-modules` where child modules did not appear as attributes in parent modules.

-   [#&#8203;1489](https://togithub.com/pytest-dev/pytest/issues/1489): Fixed some instances where teardown of higher-scoped fixtures was not happening in the reverse order they were initialized in.

## Trivial/Internal Changes

-   [#&#8203;12069](https://togithub.com/pytest-dev/pytest/issues/12069): `pluggy>=1.5.0` is now required.
-   [#&#8203;12167](https://togithub.com/pytest-dev/pytest/issues/12167): `cache <cache>`{.interpreted-text role="ref"}: create supporting files (`CACHEDIR.TAG`, `.gitignore`, etc.) in a temporary directory to provide atomic semantics.

### [`v8.1.2`](https://togithub.com/pytest-dev/pytest/releases/tag/8.1.2)

[Compare Source](https://togithub.com/pytest-dev/pytest/compare/8.1.1...8.1.2)

# pytest 8.1.2 (2024-04-26)

## Bug Fixes

-   [#&#8203;12114](https://togithub.com/pytest-dev/pytest/issues/12114): Fixed error in `pytest.approx`{.interpreted-text role="func"} when used with \[numpy]{.title-ref} arrays and comparing with other types.

</details>

---

### Configuration

📅 **Schedule**: Branch creation - "before 4am on the first day of the month" (UTC), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4zMzAuMSIsInVwZGF0ZWRJblZlciI6IjM3LjMzMC4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6WyJhdXRvbWVyZ2UiXX0=-->